language: node_js
node_js: node
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: q9PytJ384rjZha14QSxm3ROKQ35IPy7CsWJScV/Nkdg2SXWS5FXbTr0PKG/U9gkBPnVgGzTFct5AjissWRUAGbtTAwoG7GmGnv+kcDOzyrtqGwTEz7Bmu3/xDHH38/NG1tmDr8h5LwAkwutk/MpmsdXQbkAlEtsK7aZWEfw2XH8O3Dyi3FqUIn8rUuTurL8Tykx5D8aFmEsuNuW1rRIE5Tg79Y61rp92VPUci62TjE74CvhPOXXYcLX9Pccq40vi/IgeDsHSBGakCFrDZp02C4LxASNRk1O7sl1YaeFKwo/SUHxrDTTRO6jMymu6isQy9eoaZYsqajSLHvY1d1QHSpvceiR6Xlx2awG4aCvsjsrhqdkAe4Rc45UWkKWXIxBx6xI1boAKrVn3MwbZi7Igu9U9muYCJEx2pb3khs0/YaEiLgWjbAyMkmAL/z5pLKYdUJm5twIf1rduWB1zy9eeoNwJqZlXcrnXcrZOzwdVpj1fXEzALl42DQELs54q4FmG4VXtMCLqqVUkcdjDK+7vBAiJh39NGqejl+C8S62a9WHuzKsgUmu+IDqB+8E6qVY//VbOCPp7eflDyUhOwaTSQJ6JFcj5v7w1aQXJJWp5M1xShVlp0YaPwrC0TYiYvKIQAQIwiIGcAxik6qpnfNRBoBVGW6oIGikRBhZJM3HNlcU=
  app: mighty-depths-77465
  on:
    repo: leesyang/donePeriod-client
