language: node_js
node_js: node
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: C/VdS5f11iUgeKraiouX8tBmk/dR5uqvjmQwIQ2RGKzRODbjRDceXAZn1/dVdsrA7vwaD625wzNMJViN+PNQs71/QAxKCDOIMGuB1GAwsS/wP7GJevea8e320l4firNRlzBxvkLSISurEt8ReqLU/658N7pzv7sjgNXwB3TaDDadbwy5kj7+2cjlTzhq8iNGS/qkrKMKpMDZjMfvKaxrV2b3S+G3nniouN2vEMs6Ou4mHnYMOZ1NpL+C4Y2aq2FIkceF8leMlJtkIt72BCjHhZ2vd0JzGQAGDiwOK29G7Mhr1Hgg5luV74iwjPrRp+WuAk2ZY/+yDnSDv6kGnIKgM0yUGdFHLQFulFVRxCyU4qxIq+MzP+d9L3GAm48VoSs4VVD2xV0C/W3EcosnHAk0xAnJM7Lt1rsa2bEhpzPN2CTn12Mo6priEouzemXjdz4qsW7pJbyGikLHbhXHc12ggwdZb5jNdX9K+wS0Beo7ghiOCsGjnNAlcs+yMsc+rYp/YBjn5BnH2mGG8r13XPYluvDH83BhV6bC7Zg331TSw50LtIacpN7RyGQHLfgryoo+xNj+Rq7871xuoNPbXR5zP/Ss5OtKIyY9U2Qbvp22AeTjtMyD9bmF9/EDTfpY3li6UrxudXBuUZwav1Sg3igz13kI7CTJ/eFgKWSMdHHjFhQ=
  app: doneperiodapp
  on:
    repo: leesyang/donePeriod-client
